### ISSUE TITLE
Plug-in as requirement?

### ISSUE THREAD

**Issue by timonvanhasselt** [OpenVoiceOS/skill-ovos-youtube-music#7]
Maybe idea to make the YouTube plugin a requirement of the skill? https://github.com/OpenVoiceOS/ovos-ocp-youtube-plugin

**Comment by JarbasAl** [comment]
the requirement needs to be installed in ovos-audio/media, not in the skill itself

the new skill.json spec accounts for this already, when the appstores are finished this will be solved
